name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up C++ toolchain
        uses: actions/setup-cpp@v1
      - name: Build code
        run: make
